excerpt_separator: <!--end-excerpt-->
include: [doc]
defaults:
  -
    scope:
      path: "doc"
      type: "pages"
    values:
      layout: "default"

github:
  issues_url: "https://github.com/openprinting/cups/issues"
  repository_url: "https://github.com/openprinting/cups"
